language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $26d4d3953575f886bb0d2247dc2cdb724c58f374
  local_dir: build
  on:
    branch:
      - master
      - HW1
